### ISSUE TITLE
Can't use HTML in free html block?

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#162]
To reproduce log in to the admin panel in http://af53342.tizrapublisher.com/ and try to publish the design to live.

The code that seems to cause the error is in the layout override of the static page called author index. I've labeled the block "THIS ONE I THINK"

Thanks!

**Comment by daviddurand** [comment]
There's a giant markup block in the design that contains an illegal character for XML/HTML, and that's caused the problem:

```
... many lines deleted...
                <span class="t-label">Title:</span> <span class="t-value"><a href="/2u4uih" target="_blank">On The Incidence of Deposit Taxes</a></span></div>
            <div class="publicationDate t-metatag">
                <span class="t-label">Publication Date:</span> <span class="t-value">2007</span></div>
            <div class="volumeNumber t-metatag">
                <span class="t-label">Volume Number:</span> <span class="t-value">5</span></div>
            <div class="issueNumber t-metatag">
                <span class="t-label">Issue Number:</span> <span class="t-value">2</span></div>
        </div>
    </li>
    <li class="t-alphaindex-item t-item authorField">
        <span class="t-index-main">Zhang, Zhiqiang Wilson</span>
        <div class="metaData">
            <div class="paper t-metatag">
                <span class="t-label">Title:</span> <span class="t-value"><a href="/2u5d2q" target="_blank">A Study on Microfinance in China</a></span></div>
            <div class="publicationDate t-metatag">
                <span class="t-label">Publication Date:</span> <span class="t-value">2012</span></div>
            <div class="volumeNumber t-metatag">
                <span class="t-label">Volume Number:</span> <span class="t-value">10</span></div>
            <div class="issueNumber t-metatag">
                <span class="t-label">Issue Number:</span> <span class="t-value">2</span></div>
        </div>
    </li>
</ul>
" is not legal for a JDOM character content: 0x19 is not a legal XML character.
    at org.jdom.Text.setText(Text.java:188)
    at org.jdom.Text.<init>(Text.java:99)
    at com.cubchicken.layout.model.PageBlock.pageBlockToXmlElementSpecific(PageBlock.java:286)
```
